language: python
sudo: false
branches:
  only:
  - master
  - "/^\\d\\.\\d+$/"
  - "/^\\d\\.\\d+\\.\\d+(rc\\d+|\\.dev\\d+)?$/"
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 2.7
    env: TOXENV=jessie
  - python: 2.7
    env: TOXENV=pypy
  - python: 2.7
    env: TOXENV=pypy3
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
install:
- |
  if [ "$TOXENV" = "pypy" ]; then
    export PYPY_VERSION="pypy-6.0.0-linux_x86_64-portable"
    wget "https://bitbucket.org/squeaky/portable-pypy/downloads/${PYPY_VERSION}.tar.bz2"
    tar -jxf ${PYPY_VERSION}.tar.bz2
    virtualenv --python="$PYPY_VERSION/bin/pypy" "$HOME/virtualenvs/$PYPY_VERSION"
    source "$HOME/virtualenvs/$PYPY_VERSION/bin/activate"
  fi
  if [ "$TOXENV" = "pypy3" ]; then
    export PYPY_VERSION="pypy3.5-5.9-beta-linux_x86_64-portable"
    wget "https://bitbucket.org/squeaky/portable-pypy/downloads/${PYPY_VERSION}.tar.bz2"
    tar -jxf ${PYPY_VERSION}.tar.bz2
    virtualenv --python="$PYPY_VERSION/bin/pypy3" "$HOME/virtualenvs/$PYPY_VERSION"
    source "$HOME/virtualenvs/$PYPY_VERSION/bin/activate"
  fi
- pip install -U tox twine wheel codecov
script: tox
after_success:
- codecov
cache:
  directories:
  - "$HOME/.cache/pip"
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: grammy.jiang
  password:
    secure: mtYXwJq47Wju/VtxgiTN43mJOWcmw+UAE+1IVbWfiKhMWRZgy9ZjJWoRMW1nWXnRBb1AFDkU5EDuvXqErsIiO1+fcLAwxZ/pKtioklsbGoHAh9P7kWT7sYIq8ARzmNYKcQbf+QOcxNbwnXYR42t3hSL09QYIqhsHe6WYaMHbpd4x9eHiN4AZqNC2gJ92yp7Dp+pfvWdgJdZaY2p7wWfQF4eLnabehXl3L4s2CPk6BdyXca7BibJDJ5QkOLifNRH2zTkvpGOyyQoy8t5lqJVvNiizDv1ulxrle61j1jj1swg9p+eX/A6W1M44Q/9OUe9hUsK6jus2yrybW3VI3FBPuuWitIkFjGgGGxbEAFarcXzcQD4yBrgM7J1NeNtBcQ63c3Mzn82aC/GSZIe/MYo8MbUodL1JSwyjyJCelo5wMpb8cuyyKhmg2NW0YLVOzex4nuVQ3GOVs7k9zYVdz2jh1E3A4PHjhZgbFENnmwvTfxUNMC75kEV6DPyAtql67Q2B8OXAHqNZe9GxehXjLQimEeQcYaJfcxorcBKxBOMuOaSJV1wNY6U3vjU4nZEoHb4UYj2V6yrAuEAee+1A74vxQcjCItpC9a8VKAjOpSKLERQ4lixK6xmPUcyoLfJ7Iu76jtCq/NKj1N2qeRg35Ovt+txGqGH/btFj+J+KY2bgVow=
  on:
    condition: "$TOXENV == py27"
