language: python
sudo: false
branches:
  only:
    - master
    - /^\d\.\d+$/
    - /^\d\.\d+\.\d+(rc\d+|\.dev\d+)?$/
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 2.7
      env: TOXENV=jessie
    - python: 2.7
      env: TOXENV=pypy
    - python: 2.7
      env: TOXENV=pypy3
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
#    - python: 3.6
#      env: TOXENV=docs
install:
  - |
      if [ "$TOXENV" = "pypy" ]; then
        export PYPY_VERSION="pypy-6.0.0-linux_x86_64-portable"
        wget "https://bitbucket.org/squeaky/portable-pypy/downloads/${PYPY_VERSION}.tar.bz2"
        tar -jxf ${PYPY_VERSION}.tar.bz2
        virtualenv --python="$PYPY_VERSION/bin/pypy" "$HOME/virtualenvs/$PYPY_VERSION"
        source "$HOME/virtualenvs/$PYPY_VERSION/bin/activate"
      fi
      if [ "$TOXENV" = "pypy3" ]; then
        export PYPY_VERSION="pypy3.5-5.9-beta-linux_x86_64-portable"
        wget "https://bitbucket.org/squeaky/portable-pypy/downloads/${PYPY_VERSION}.tar.bz2"
        tar -jxf ${PYPY_VERSION}.tar.bz2
        virtualenv --python="$PYPY_VERSION/bin/pypy3" "$HOME/virtualenvs/$PYPY_VERSION"
        source "$HOME/virtualenvs/$PYPY_VERSION/bin/activate"
      fi
  - pip install -U tox twine wheel codecov

script: tox
after_success:
  - codecov
#notifications:
#  slack:
#    rooms:
#      - secure: zsDJgHzhPoAIs8OsOiv5wmNsck++hjZljeYAfKh25UwW8X97Rqvq5r9LMlQzIHf2a638AbsubDNeSbrxxu6cFDeeIFngG1EO5mOSWzKr18LM5pFb0GVlImKzZpKgLqKmaD5ATYXnvUaHjEHgO45TzjIsbwo9P4vRU5C/lGYwfdv/J82hP0OUo02HqWGkwpG0aeuzs1bJZKjS/RdHROt0SQpRfVB8hi4HHrQILgliuVcpvIk46FgRB49VmzpAGuQfJtB06gj8o6tL/1JlXQ9/ElrHwEJyGjiyeP/nP8qit+i9TTlHGT9k0s9oYuXWM8OlgKfKE13Mo8fVRaAhVv9DRcwtNpX5M0RtC5bEjCPQIL14ky4ymeSlGchmy37jTKJCNHm4St4CtodCrF5J77h8Gkjx9tkZOhf4Rd8veMMgv/gj8pyt3asJ8PMDvREjF4n4mRPy5SB53anEhrFXE801KOpqb4Ffsjv2DBJmuAId+OmHLs69jHeiwxkBDaeKDr6rpiiKQaZNbDw5KxjEafEtclVmSdprq57Og2SPaCR1TrUu3SVyUjVoWNj6olKS9ALoiDAVLBprbyBsSS9gYwfTlSBNxCsMApQksjmo0/S6n/FwyCvn4AZZVziLVtVxPBY0sUpRBNySkTTrQzpCiEPNmv7tU8d0ZcVI508/WALzIQ0=
cache:
  directories:
    - $HOME/.cache/pip
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: grammy.jiang
  password:
    secure: ZZCaljv2kevryQAPirBO+DcvjPPJZDcq7Cnfr4ncubnQZ3ApFuxO7spLe9PUNDBrIkot8e/CvC4NqVmZvcepHVyqouCOElh3sXERK4RwGywTPHQLvbqUGeic40aOHu0nh/6BGfy6cyubckCbNYN0oTpChAv397HPGfzggCKeUPv2GUVeBUYoCERFntPo6ds7IJszuWABozj1djFNhiAYKdMU9vqpkiXRof7RjuJGEiqHwCgHsp7qUvwSM2A3UgbIMFJ8uGF3YooWz18zUA8y/QJ3X/JNdoTZQJfOhNtIPK+Z5o2LqDpSG6sZdiyONCBK6cCBNWLY9V/cybtkQC6U9LyLRuRhSjYTQuwuxpy7BWp8v0mmFTd/uczPyyWZfz8z3Wg0oX6BpfIx2tjFaR+WBv/Ei7OOVHi1Og2YKbQ/trvOPR77z8cIadOjD1e8VioNGBRfSgQKZMDDr0ErCc3ihDS2Dqe1kPKF5gSgAr9Iq+lOueOjVJjK1iyzkCgP2smq+z2NPFXvshfIp7S2ypKjtpkG6JKxdtaOQ4AcNv21qr2YIHGxylEbyljYNFxGLVApxsK8Yb1YoP3PJntCH53SJOYiCL6A3+jolKw8j99H+xVlqH5wGxi7aR0sM48AnA25DBCKpFo9e4FqxBL7gEu0lumhmbUhHPNH3GM81h63uhI=
  on:
  #   branch: master
  #   tags: true
  #   repo: grammy-jiang/scrapy-httpproxy
    condition: "$TOXENV == py27"
